apiVersion: apps/v1
kind: Deployment
metadata:
  name: charles-test-1
  labels:
    app: charles
spec:
  replicas: 3
  selector:
    matchLabels:
      app: charles
  template:
    metadata:
      labels:
        app: charles
    spec:
      containers:
      - name: charles
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 80